### ISSUE TITLE
How to handle event on enter

### ISSUE THREAD

**Issue by rambhual** [FireLemons/AbbreviationAutocompleteReact#1]
How to handle event on enter

**Comment by FireLemons** [comment]
I'm sorry what's the question? When you select an element in the dropdown and hit enter it triggers an onSelect event

**Comment by rambhual** [comment]
Sorry 
Actually I need to handle enter event without select from list below.

**Comment by FireLemons** [comment]
Well in that case it's probably easiest to fork the repo and modify the component code yourself and then import your version of the component. I don't plan on adding support for basic javascript events.

**Comment by FireLemons** [comment]
you want to modify `src/abbreviation-autocomplete.jsx`
